// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooVrt.Models;

namespace ZooVrt.Migrations
{
    [DbContext(typeof(ContextKlasa))]
    [Migration("20220120210249_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ZooVrt.Models.Direktor", b =>
                {
                    b.Property<int>("DirektorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DirektorIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirektorPrezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZooloskiVrtId")
                        .HasColumnType("int");

                    b.HasKey("DirektorId");

                    b.HasIndex("ZooloskiVrtId");

                    b.ToTable("Direktori");
                });

            modelBuilder.Entity("ZooVrt.Models.Zivotinja", b =>
                {
                    b.Property<int>("ZivotinjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImeVrste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrenutnaKolicina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZooloskiVrtId")
                        .HasColumnType("int");

                    b.HasKey("ZivotinjaId");

                    b.HasIndex("ZooloskiVrtId");

                    b.ToTable("Zivotinje");
                });

            modelBuilder.Entity("ZooVrt.Models.ZooloskiVrt", b =>
                {
                    b.Property<int>("ZooloskiVrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZooloskiVrtId");

                    b.ToTable("ZooloskiVrtovi");
                });

            modelBuilder.Entity("ZooVrt.Models.Direktor", b =>
                {
                    b.HasOne("ZooVrt.Models.ZooloskiVrt", "ZooloskiVrt")
                        .WithMany("Direktor")
                        .HasForeignKey("ZooloskiVrtId");

                    b.Navigation("ZooloskiVrt");
                });

            modelBuilder.Entity("ZooVrt.Models.Zivotinja", b =>
                {
                    b.HasOne("ZooVrt.Models.ZooloskiVrt", "ZooloskiVrt")
                        .WithMany("Zivotinje")
                        .HasForeignKey("ZooloskiVrtId");

                    b.Navigation("ZooloskiVrt");
                });

            modelBuilder.Entity("ZooVrt.Models.ZooloskiVrt", b =>
                {
                    b.Navigation("Direktor");

                    b.Navigation("Zivotinje");
                });
#pragma warning restore 612, 618
        }
    }
}
